name: Infra Deploy

on:
  push:
    paths:
      - 'infra/**'

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve \
          -var="location=${{ env.AZURE_LOCATION }}" \
          -var="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
          -var="acr_name=${{ env.ACR_NAME }}" \
          -var="env_name=${{ env.ENV_NAME }}" \
          -var="app_name=${{ env.APP_NAME }}"
    env:
      AZURE_LOCATION: "East US"
      RESOURCE_GROUP_NAME: "WanchooResourceGroup1"
      ACR_NAME: "vikasacr1"
      ENV_NAME: "vikas-env1"
      APP_NAME: "flaskapi-app1"
